### ISSUE TITLE
"Uncaught TypeError: serviceCallEvent.data.indexOf is not a function"

### ISSUE THREAD

**Issue by bradvogel** [izuzak/pmrpc#19]
I'm using your library inside a window that is getting external postmessages. Those messages are in an object format, so 'indexOf' isn't defined. Can you add protection to make sure serviceCallEvent.data is a string before calling indexOf?

**Comment by izuzak** [comment]
@bradvogel Sure, sounds like a good idea. Happy to review and merge a PR if you'd like to work on that?
